package avro2s.wire.compiler

import org.apache.avro.Schema
import SchemaModel.{Definition, Logical, Value}

final case class GeneratedSource(relativePath: String, content: String)

/** Schema-first generation. The emitted sources have no Apache Avro dependency. */
object CodeGenerator:
  def generate(schema: Schema, config: GeneratorConfig = GeneratorConfig()): Vector[GeneratedSource] =
    val definitions = SchemaModel.definitions(schema, config)
    val byName = definitions.map(definition => definition.name -> definition).toMap
    definitions.map(generateDefinition(_, byName, config))

  private def generateDefinition(definition: Definition, definitions: Map[String, Definition], config: GeneratorConfig): GeneratedSource =
    val emitter = Emitter(config, definitions)
    val fullName = config.mappedFullName(definition.name)
    val parts = fullName.split("\\.").toVector
    val localName = ScalaNames.escaped(parts.last)
    val qualifiedName = ScalaNames.qualified(fullName)
    val header =
      "// Generated by avro2s.wire. Do not edit.\n" +
        (if parts.size > 1 then s"package ${parts.init.map(ScalaNames.escaped).mkString(".")}\n\n" else "\n")

    val (model, json, read, write, construct) = definition match
      case Definition.Record(_, fields, json) =>
        val parameters = fields.map { field =>
          s"${ScalaNames.escaped(field.scalaName)}: ${emitter.scalaType(field.value)}"
        }.mkString(", ")
        val reads = fields.zipWithIndex.map { (field, index) =>
          s"val field$index: ${emitter.scalaType(field.value)} = ${emitter.read(field.value)}"
        }
        val constructor = s"new $qualifiedName(${fields.indices.map(i => s"field$i").mkString(", ")})"
        val read = "in.enterRecord()\ntry {\n" + indent((reads :+ constructor).mkString("\n"), 2) +
          "\n} finally in.leaveRecord()"
        val writes = fields.map { field =>
          emitter.write(field.value, s"value.${ScalaNames.escaped(field.scalaName)}")
        }
        val construct = s"new $qualifiedName(${fields.zipWithIndex.map((field, index) => s"values($index).asInstanceOf[${emitter.scalaType(field.value)}]").mkString(", ")})"
        (s"final case class $localName($parameters)\n", json, read,
          if writes.isEmpty then "()" else writes.mkString("\n"), construct)

      case Definition.Enumeration(_, symbols, json) =>
        val cases = ScalaNames.memberNames(symbols, ScalaNames.enumMembers(config.generateStackSafeCodecs) + parts.last, "symbol")
        val model = s"enum $localName:\n" + cases.map(name => s"  case ${ScalaNames.escaped(name)}").mkString("\n") + "\n"
        val readCases = cases.zipWithIndex.map { (name, index) =>
          s"case $index => $qualifiedName.${ScalaNames.escaped(name)}"
        }.mkString("\n")
        val error = ScalaNames.literal(s"Invalid enum index for $fullName: ")
        val read = "in.readEnum() match {\n" + indent(readCases, 2) +
          s"\n  case index => throw new _root_.avro2s.wire.runtime.AvroDecodingException($error + index)\n}"
        (model, json, read, "out.writeEnum(value.ordinal)", s"$qualifiedName.fromOrdinal(values(0).asInstanceOf[_root_.scala.Int])")

      case Definition.Fixed(_, size, logical, json) =>
        val message = ScalaNames.literal(s"$fullName requires exactly $size bytes")
        val valueType = logical.fold("_root_.avro2s.wire.runtime.Bytes")(_.scalaType(config.decimalType))
        val model = s"final case class $localName(value: $valueType)" +
          logical.fold(s":\n  _root_.scala.Predef.require(value.size == $size, $message)\n")(_ => "\n")
        val read = logical.fold(s"in.readFixed($size)")(emitter.readLogical(_, Some(size)))
        val write = logical.fold("out.writeFixed(value.value)")(emitter.writeLogical(_, "value.value", Some(size)))
        (model, json, s"new $qualifiedName($read)", write,
          s"new $qualifiedName(values(0).asInstanceOf[$valueType])")

    val references = reachableDefinitions(definition, definitions).map { name =>
      s"case ${ScalaNames.literal(name)} => ${ScalaNames.qualified(config.mappedFullName(name))}.codec"
    }.mkString("\n")

    val decimalRepresentation = config.decimalType match
      case DecimalType.Scala => ""
      case DecimalType.Java =>
        "    override val decimalRepresentation: _root_.avro2s.wire.runtime.DecimalRepresentation = _root_.avro2s.wire.runtime.DecimalRepresentation.Java\n\n"

    val rawLogicalTypes =
      if config.rawLogicalTypes.isEmpty then ""
      else "    override val rawLogicalTypes: _root_.scala.collection.immutable.Set[_root_.java.lang.String] = " +
        config.rawLogicalTypes.map(ScalaNames.literal).mkString("_root_.scala.collection.immutable.Set(", ", ", ")\n\n")

    val companion = s"\nobject $localName:\n" +
      s"  val schemaJson: _root_.java.lang.String = ${ScalaNames.stringExpression(json)}\n\n" +
      s"  given codec: _root_.avro2s.wire.runtime.AvroCodec[$qualifiedName] with\n" +
      s"    override val schemaJson: _root_.java.lang.String = $qualifiedName.schemaJson\n\n" +
      decimalRepresentation +
      rawLogicalTypes +
      s"    override def read(in: _root_.avro2s.wire.runtime.AvroInput): $qualifiedName =\n" + indent(read, 6) + "\n\n" +
      s"    override def write(value: $qualifiedName, out: _root_.avro2s.wire.runtime.AvroOutput): _root_.scala.Unit =\n" +
      indent(write, 6) + "\n\n" +
      s"    override def construct(values: _root_.scala.Array[_root_.scala.Any]): $qualifiedName =\n" + indent(construct, 6) + "\n\n" +
      "    override def namedCodec(fullName: _root_.java.lang.String): _root_.avro2s.wire.runtime.AvroCodec[?] =\n" +
      "      fullName match {\n" + indent(references, 8) + "\n        case _ => super.namedCodec(fullName)\n      }\n"

    if !config.generateStackSafeCodecs then
      return GeneratedSource(parts.mkString("/") + ".scala", header + model + companion)

    // Generate the alternative separately so direct codec code, including fresh
    // local names and specialised collection hooks, stays byte-for-byte stable.
    val safeEmitter = Emitter(config, definitions, Some(definition.name))
    val selfReference = definition match
      case Definition.Record(_, fields, _) => fields.exists(field => safeEmitter.refersToSelf(field.value))
      case _ => false
    val (safeRead, safeWrite) = definition match
      case Definition.Record(_, fields, _) if fields.exists(field => !safeEmitter.isDirectLeaf(field.value)) =>
        (safeEmitter.readFrame(qualifiedName, fields), safeEmitter.writeFrame(qualifiedName, fields))
      case _ =>
        // A leaf record has no recursive child traversal. One suspended direct
        // body keeps primitive fields unboxed and retains its try/finally hooks.
        (s"${safeEmitter.step}.delay {\n" + indent(read, 2) + "\n}",
          s"${safeEmitter.step}.delay {\n" + indent(write, 2) + "\n}")

    val safeReferences = reachableDefinitions(definition, definitions).map { name =>
      s"case ${ScalaNames.literal(name)} => ${ScalaNames.qualified(config.mappedFullName(name))}.stackSafeCodec"
    }.mkString("\n")
    val safeCompanion =
      s"\n  lazy val stackSafeCodec: _root_.avro2s.wire.runtime.codegen.StackSafeCodec[$qualifiedName] =\n" +
      s"    new _root_.avro2s.wire.runtime.codegen.StackSafeCodec[$qualifiedName]" +
      (if selfReference then " { codecSelf =>\n" else ":\n") +
      s"      override val schemaJson: _root_.java.lang.String = $qualifiedName.schemaJson\n\n" +
      (if decimalRepresentation.isEmpty then "" else indent(decimalRepresentation.stripTrailing(), 2) + "\n\n") +
      (if rawLogicalTypes.isEmpty then "" else indent(rawLogicalTypes.stripTrailing(), 2) + "\n\n") +
      s"      override def readStep(in: _root_.avro2s.wire.runtime.AvroInput): ${safeEmitter.step}[$qualifiedName] =\n" +
      indent(safeRead, 8) + "\n\n" +
      s"      override def writeStep(value: $qualifiedName, out: _root_.avro2s.wire.runtime.AvroOutput): ${safeEmitter.step}[_root_.scala.Unit] =\n" +
      indent(safeWrite, 8) + "\n\n" +
      s"      override def construct(values: _root_.scala.Array[_root_.scala.Any]): $qualifiedName =\n" +
      indent(construct, 8) + "\n\n" +
      "      override def namedCodec(fullName: _root_.java.lang.String): _root_.avro2s.wire.runtime.AvroCodec[?] =\n" +
      "        fullName match {\n" + indent(safeReferences, 10) + "\n          case _ => super.namedCodec(fullName)\n        }\n" +
      (if selfReference then "    }\n" else "")
    GeneratedSource(parts.mkString("/") + ".scala", header + model + companion + safeCompanion)

  private def reachableDefinitions(root: Definition, definitions: Map[String, Definition]): Vector[String] =
    val seen = scala.collection.mutable.Set.empty[String]
    def visitValue(value: Value): Unit = value match
      case Value.Named(name) => visitDefinition(definitions(name))
      case Value.ArrayOf(element) => visitValue(element)
      case Value.MapOf(element) => visitValue(element)
      case Value.Optional(element, _, _) => visitValue(element)
      case Value.Union(branches) => branches.foreach(visitValue)
      case _ => ()
    def visitDefinition(definition: Definition): Unit =
      if seen.add(definition.name) then definition match
        case Definition.Record(_, fields, _) => fields.foreach(field => visitValue(field.value))
        case _ => ()
    visitDefinition(root)
    seen.toVector.sorted

  private def indent(text: String, spaces: Int): String =
    text.linesIterator.map(" " * spaces + _).mkString("\n")

  private final class Emitter(config: GeneratorConfig, definitions: Map[String, Definition], selfName: Option[String] = None):
    val step = "_root_.avro2s.wire.runtime.codegen.Step"
    val stackSafe = "_root_.avro2s.wire.runtime.codegen.StackSafe"
    private var sequence = 0
    private def fresh(prefix: String): String =
      sequence += 1
      s"${prefix}$sequence"

    def refersToSelf(value: Value): Boolean = value match
      case Value.Named(name) => selfName.contains(name)
      case Value.ArrayOf(element) => refersToSelf(element)
      case Value.MapOf(element) => refersToSelf(element)
      case Value.Optional(element, _, _) => refersToSelf(element)
      case Value.Union(branches) => branches.exists(refersToSelf)
      case _ => false

    // A writer frame otherwise needs no owning-codec capture, so only recursive
    // reads use the self alias; writers retain the companion lookup.
    private def readStepCodec(name: String): String =
      if selfName.contains(name) then "codecSelf"
      else s"${ScalaNames.qualified(config.mappedFullName(name))}.stackSafeCodec"

    /** Scalar leaves never traverse a record or collection. Option and union
      * dispatch can stay in the current state when every branch is scalar.
      */
    private def isScalarLeaf(value: Value): Boolean = value match
      case Value.Named(name) => definitions(name) match
        case Definition.Record(_, _, _) => false
        case _ => true
      case Value.ArrayOf(_) | Value.MapOf(_) => false
      case Value.Optional(element, _, _) => isScalarLeaf(element)
      case Value.Union(branches) => branches.forall(isScalarLeaf)
      case _ => true

    /** Batch scalar IO and one collection layer with scalar elements. Nested
      * collections must return to the driver: direct collection writers nest
      * foreach callbacks even when their schemas contain no named records.
      */
    def isDirectLeaf(value: Value): Boolean = value match
      case Value.ArrayOf(element) => isScalarLeaf(element)
      case Value.MapOf(element) => isScalarLeaf(element)
      case Value.Optional(element, _, _) => isDirectLeaf(element)
      case Value.Union(branches) => branches.forall(isDirectLeaf)
      case _ => isScalarLeaf(value)

    /** A frame is private to one operation. Typed slots avoid boxing primitive
      * fields while the driver retains the same frame across child operations.
      */
    private final class States:
      private val bodies = scala.collection.mutable.ArrayBuffer.empty[String]
      def reserve(): Int =
        val index = bodies.size
        bodies += ""
        index
      def update(index: Int, body: String): Unit = bodies(index) = body
      def add(body: String): Int =
        val index = reserve()
        update(index, body)
        index
      def dispatch: String =
        val cases = bodies.zipWithIndex.map { (body, index) =>
          s"case $index =>\n" + indent(body, 2)
        }.mkString("\n")
        "while true do {\n  phase match {\n" + indent(cases, 4) +
          "\n    case _ => throw new _root_.java.lang.IllegalStateException(\"Invalid generated codec phase\")\n  }\n}\n" +
          "throw new _root_.java.lang.IllegalStateException(\"Unreachable generated codec phase\")"

    private def initialValue(value: Value): String = value match
      case Value.Primitive(Schema.Type.BOOLEAN) => "false"
      case Value.Primitive(Schema.Type.INT) => "0"
      case Value.Primitive(Schema.Type.LONG) => "0L"
      case Value.Primitive(Schema.Type.FLOAT) => "0.0f"
      case Value.Primitive(Schema.Type.DOUBLE) => "0.0d"
      case _ => s"null.asInstanceOf[${scalaType(value)}]"

    def readFrame(qualifiedName: String, fields: Vector[SchemaModel.Field]): String =
      val states = new States
      def fieldsFrom(from: Int): Int =
        val state = states.reserve()
        var index = from
        val prefix = Vector.newBuilder[String]
        if from == 0 then prefix += "in.enterRecord()\nentered = true"
        while index < fields.size && isDirectLeaf(fields(index).value) do
          prefix += s"field$index = ${read(fields(index).value)}"
          index += 1
        if index == fields.size then
          prefix += s"answer = new $qualifiedName(${fields.indices.map(i => s"field$i").mkString(", ")})\nreturn null"
        else
          val following = fieldsFrom(index + 1)
          prefix += readFrameValue(fields(index).value, result => s"field$index = $result", following, states)
        states.update(state, prefix.result().mkString("\n"))
        state
      fieldsFrom(0)
      val slots = fields.zipWithIndex.map { (field, index) =>
        s"private var field$index: ${scalaType(field.value)} = ${initialValue(field.value)}"
      }.mkString("\n")
      s"new $step.Frame[$qualifiedName] {\n" +
        "  private var phase: _root_.scala.Int = 0\n  private var entered: _root_.scala.Boolean = false\n" +
        s"  private var answer: $qualifiedName = null\n" + indent(slots, 2) + "\n\n" +
        s"  override def advance(completed: _root_.scala.Any): $step[?] = {\n" + indent(states.dispatch, 4) + "\n  }\n\n" +
        s"  override def result: $qualifiedName = answer\n\n" +
        "  override def cleanup(): _root_.scala.Unit = {\n    if entered then {\n      entered = false\n      in.leaveRecord()\n    }\n  }\n}"

    private def readFrameValue(value: Value, store: String => String, following: Int, states: States): String =
      if isDirectLeaf(value) then store(read(value)) + s"\nphase = $following"
      else value match
        case Value.Optional(element, nullIndex, valueIndex) =>
          "in.readIndex() match {\n" +
            s"  case $nullIndex =>\n    in.readNull()\n" + indent(store("_root_.scala.None") + s"\nphase = $following", 4) + "\n" +
            s"  case $valueIndex =>\n" + indent(readFrameValue(element, result => store(s"_root_.scala.Some($result)"), following, states), 4) +
            "\n  case index => throw new _root_.avro2s.wire.runtime.AvroDecodingException(\"Invalid nullable union index: \" + index)\n}"
        case Value.Union(branches) =>
          val optional = branches.size > 1 && branches.exists(isNull)
          val cases = branches.zipWithIndex.map { (branch, index) =>
            val body =
              if optional && isNull(branch) then "in.readNull()\n" + store("_root_.scala.None") + s"\nphase = $following"
              else readFrameValue(branch, result => store(if optional then s"_root_.scala.Some($result)" else result), following, states)
            s"case $index =>\n" + indent(body, 2)
          }.mkString("\n")
          "in.readIndex() match {\n" + indent(cases, 2) +
            "\n  case index => throw new _root_.avro2s.wire.runtime.AvroDecodingException(\"Invalid union index: \" + index)\n}"
        case _ =>
          val resume = states.add(store(s"completed.asInstanceOf[${scalaType(value)}]") + s"\nphase = $following")
          s"phase = $resume\nreturn ${readStep(value)}"

    def writeFrame(qualifiedName: String, fields: Vector[SchemaModel.Field]): String =
      val states = new States
      def fieldsFrom(from: Int): Int =
        val state = states.reserve()
        var index = from
        val prefix = Vector.newBuilder[String]
        while index < fields.size && isDirectLeaf(fields(index).value) do
          val field = fields(index)
          prefix += write(field.value, s"value.${ScalaNames.escaped(field.scalaName)}")
          index += 1
        if index == fields.size then prefix += "return null"
        else
          val following = fieldsFrom(index + 1)
          val field = fields(index)
          prefix += writeFrameValue(field.value, s"value.${ScalaNames.escaped(field.scalaName)}", following)
        states.update(state, prefix.result().mkString("\n"))
        state
      fieldsFrom(0)
      s"new $step.Frame[_root_.scala.Unit] {\n  private var phase: _root_.scala.Int = 0\n\n" +
        s"  override def advance(completed: _root_.scala.Any): $step[?] = {\n" + indent(states.dispatch, 4) + "\n  }\n\n" +
        "  override def result: _root_.scala.Unit = ()\n}"

    private def writeFrameValue(value: Value, expression: String, following: Int): String =
      if isDirectLeaf(value) then write(value, expression) + s"\nphase = $following"
      else value match
        case Value.Optional(element, nullIndex, valueIndex) =>
          s"if $expression.isEmpty then {\n  out.writeIndex($nullIndex)\n  out.writeNull()\n  phase = $following\n} else {\n  out.writeIndex($valueIndex)\n" +
            indent(writeFrameValue(element, s"$expression.get", following), 2) + "\n}"
        case Value.Union(branches) =>
          val nullIndex = branches.indexWhere(isNull)
          if branches.size == 1 then "out.writeIndex(0)\n" + writeFrameValue(branches.head, expression, following)
          else if nullIndex >= 0 then
            s"if $expression.isEmpty then {\n  out.writeIndex($nullIndex)\n  out.writeNull()\n  phase = $following\n} else {\n" +
              indent(writeFrameUnion(branches.zipWithIndex.filterNot((branch, _) => isNull(branch)), s"$expression.get", following), 2) + "\n}"
          else writeFrameUnion(branches.zipWithIndex, expression, following)
        case _ => s"phase = $following\nreturn ${writeStep(value, expression)}"

    private def writeFrameUnion(branches: Vector[(Value, Int)], expression: String, following: Int): String =
      val cases = branches.map { (branch, index) =>
        val binding = fresh("branch")
        val (pattern, typed) = branch match
          case Value.ArrayOf(_) => ("_root_.scala.collection.immutable.Vector[?]", s"$binding.asInstanceOf[${scalaType(branch)}]")
          case Value.MapOf(_) => ("_root_.scala.collection.immutable.Map[?, ?]", s"$binding.asInstanceOf[${scalaType(branch)}]")
          case _ => (scalaType(branch), binding)
        s"case $binding: $pattern =>\n" + indent(s"out.writeIndex($index)\n" + writeFrameValue(branch, typed, following), 2)
      }.mkString("\n")
      s"($expression: _root_.scala.Any) match {\n" + indent(cases, 2) +
        "\n  case _ => throw new _root_.java.lang.IllegalArgumentException(\"Value does not match any Avro union branch\")\n}"

    def scalaType(value: Value): String = value match
      case Value.Primitive(Schema.Type.NULL)    => "_root_.scala.Null"
      case Value.Primitive(Schema.Type.BOOLEAN) => "_root_.scala.Boolean"
      case Value.Primitive(Schema.Type.INT)     => "_root_.scala.Int"
      case Value.Primitive(Schema.Type.LONG)    => "_root_.scala.Long"
      case Value.Primitive(Schema.Type.FLOAT)   => "_root_.scala.Float"
      case Value.Primitive(Schema.Type.DOUBLE)  => "_root_.scala.Double"
      case Value.Primitive(Schema.Type.STRING)  => "_root_.java.lang.String"
      case Value.Primitive(Schema.Type.BYTES)   => "_root_.avro2s.wire.runtime.Bytes"
      case Value.Primitive(other) => throw GenerationException(s"Unexpected primitive schema: $other")
      case Value.LogicalValue(logical) => logical.scalaType(config.decimalType)
      case Value.WrappedLogical(logical) => s"_root_.avro2s.wire.runtime.$logical"
      case Value.Named(name) => ScalaNames.qualified(config.mappedFullName(name))
      case Value.ArrayOf(element) => s"_root_.scala.collection.immutable.Vector[${scalaType(element)}]"
      case Value.MapOf(element) => s"_root_.scala.collection.immutable.Map[_root_.java.lang.String, ${scalaType(element)}]"
      case Value.Optional(element, _, _) => s"_root_.scala.Option[${scalaType(element)}]"
      case Value.Union(branches) =>
        val nonNull = branches.filterNot(isNull)
        val union = nonNull.map(scalaType).mkString(" | ")
        if nonNull.isEmpty then "_root_.scala.Null"
        else if nonNull.size != branches.size then s"_root_.scala.Option[$union]"
        else union

    private def isNull(value: Value): Boolean = value == Value.Primitive(Schema.Type.NULL)

    def readLogical(logical: Logical, fixedSize: Option[Int] = None): String =
      val (method, arguments) = logicalArguments(logical, fixedSize)
      s"_root_.avro2s.wire.runtime.LogicalValues.read$method(in$arguments)"

    def writeLogical(logical: Logical, expression: String, fixedSize: Option[Int] = None): String =
      val (method, arguments) = logicalArguments(logical, fixedSize)
      s"_root_.avro2s.wire.runtime.LogicalValues.write$method($expression, out$arguments)"

    private def logicalArguments(logical: Logical, fixedSize: Option[Int]): (String, String) = logical match
      case Logical.Decimal(precision, scale) =>
        val prefix = if config.decimalType == DecimalType.Java then "Java" else ""
        fixedSize match
          case Some(size) => (s"${prefix}FixedDecimal", s", $size, $precision, $scale")
          case None => (s"${prefix}Decimal", s", $precision, $scale")
      case Logical.BigDecimal =>
        (if config.decimalType == DecimalType.Java then "JavaBigDecimal" else "BigDecimal", "")
      case Logical.Uuid if fixedSize.nonEmpty => ("FixedUuid", "")
      case other => (other.toString, "")

    private def primitiveSuffix(kind: Schema.Type): String = kind match
      case Schema.Type.BOOLEAN => "Boolean"
      case Schema.Type.INT     => "Int"
      case Schema.Type.LONG    => "Long"
      case Schema.Type.FLOAT   => "Float"
      case Schema.Type.DOUBLE  => "Double"
      case Schema.Type.STRING  => "String"
      case Schema.Type.BYTES   => "Bytes"
      case other => throw GenerationException(s"Unexpected binary primitive: $other")

    def read(value: Value): String = value match
      case Value.Primitive(Schema.Type.NULL) => "{ in.readNull(); null }"
      case Value.Primitive(kind) => s"in.read${primitiveSuffix(kind)}()"
      case Value.LogicalValue(logical) => readLogical(logical)
      case Value.WrappedLogical(logical) => s"new _root_.avro2s.wire.runtime.$logical(${readLogical(logical)})"
      case Value.Named(name) => s"${ScalaNames.qualified(config.mappedFullName(name))}.codec.read(in)"
      case Value.Optional(element, nullIndex, valueIndex) =>
        "in.readIndex() match {\n" +
          s"  case $nullIndex => in.readNull(); _root_.scala.None\n" +
          s"  case $valueIndex => _root_.scala.Some(${read(element)})\n" +
          "  case index => throw new _root_.avro2s.wire.runtime.AvroDecodingException(\"Invalid nullable union index: \" + index)\n}"
      case Value.ArrayOf(element) => readCollection(element, isMap = false)
      case Value.MapOf(element) => readCollection(element, isMap = true)
      case Value.Union(branches) =>
        val optional = branches.size > 1 && branches.exists(isNull)
        val cases = branches.zipWithIndex.map { (branch, index) =>
          val result =
            if optional && isNull(branch) then "{ in.readNull(); _root_.scala.None }"
            else if optional then s"_root_.scala.Some(${read(branch)})"
            else read(branch)
          s"case $index => $result"
        }.mkString("\n")
        "in.readIndex() match {\n" + indent(cases, 2) +
          "\n  case index => throw new _root_.avro2s.wire.runtime.AvroDecodingException(\"Invalid union index: \" + index)\n}"

    private def readCollection(element: Value, isMap: Boolean): String =
      val builder = fresh("builder")
      val remaining = fresh("remaining")
      val key = fresh("key")
      val item = fresh("item")
      val collection = if isMap then "Map" else "Vector"
      val arguments = if isMap then s"_root_.java.lang.String, ${scalaType(element)}" else scalaType(element)
      val start = if isMap then "readMapStart" else "readArrayStart"
      val next = if isMap then "mapNext" else "arrayNext"
      // Map's generic builder stages the first four distinct keys in compact
      // maps before forwarding every subsequent entry to a HashMap builder.
      // Start that builder directly when this block already exceeds the compact
      // representation; small maps still retain their compact representation.
      val newBuilder = if isMap then
        s"if $remaining > 4L then _root_.scala.collection.immutable.HashMap.newBuilder[$arguments] " +
          s"else _root_.scala.collection.immutable.Map.newBuilder[$arguments]"
      else s"_root_.scala.collection.immutable.Vector.newBuilder[$arguments]"
      val entry =
        if isMap then s"val $key = in.readString()\nval $item: ${scalaType(element)} = ${read(element)}\n$builder += (($key, $item))"
        else s"$builder += (${read(element)})"
      s"{\n  var $remaining = in.$start()\n" +
        s"  if $remaining == 0L then _root_.scala.collection.immutable.$collection.empty[$arguments]\n" +
        s"  else {\n    val $builder = $newBuilder\n" +
        s"    while $remaining != 0L do {\n" +
        s"      while $remaining > 0L do {\n" + indent(entry, 8) + s"\n        $remaining -= 1L\n      }\n" +
        s"      $remaining = in.$next()\n    }\n    $builder.result()\n  }\n}"

    /** Every generated step method suspends before visiting fields or children,
      * so named child steps can join the caller's driver without another defer.
      * Calling a child's public read/write here would start a nested runner and
      * bring back JVM-stack recursion.
      */
    def readStep(value: Value): String = value match
      case leaf if isDirectLeaf(leaf) => s"$step.delay {\n" + indent(read(leaf), 2) + "\n}"
      case Value.Named(name) =>
        s"${readStepCodec(name)}.readStep(in)"
      case Value.ArrayOf(element) =>
        s"$stackSafe.readArray[${scalaType(element)}](in) {\n" + indent(readStep(element), 2) + "\n}"
      case Value.MapOf(element) =>
        s"$stackSafe.readMap[${scalaType(element)}](in) {\n" + indent(readStep(element), 2) + "\n}"
      case Value.Optional(element, nullIndex, valueIndex) =>
        s"$step.defer[${scalaType(value)}] {\n  in.readIndex() match {\n" +
          s"    case $nullIndex => $step.delay { in.readNull(); _root_.scala.None }\n" +
          s"    case $valueIndex => ${readStep(element)}.map(item => _root_.scala.Some(item))\n" +
          "    case index => throw new _root_.avro2s.wire.runtime.AvroDecodingException(\"Invalid nullable union index: \" + index)\n  }\n}"
      case Value.Union(branches) =>
        val optional = branches.size > 1 && branches.exists(isNull)
        val cases = branches.zipWithIndex.map { (branch, index) =>
          val result =
            if optional && isNull(branch) then s"$step.delay { in.readNull(); _root_.scala.None }"
            else if optional then readStep(branch) + ".map(item => _root_.scala.Some(item))"
            else readStep(branch)
          s"case $index => $result"
        }.mkString("\n")
        s"$step.defer[${scalaType(value)}] {\n  in.readIndex() match {\n" + indent(cases, 4) +
          "\n    case index => throw new _root_.avro2s.wire.runtime.AvroDecodingException(\"Invalid union index: \" + index)\n  }\n}"
      case _ => s"$step.delay { ${read(value)} }"

    def writeStep(value: Value, expression: String): String = value match
      case leaf if isDirectLeaf(leaf) => s"$step.delay {\n" + indent(write(leaf, expression), 2) + "\n}"
      case Value.Named(name) =>
        s"${ScalaNames.qualified(config.mappedFullName(name))}.stackSafeCodec.writeStep($expression, out)"
      case Value.Optional(element, nullIndex, valueIndex) =>
        s"$step.defer {\n  if $expression.isEmpty then {\n    out.writeIndex($nullIndex)\n    out.writeNull()\n    $step.done(())\n  } else {\n    out.writeIndex($valueIndex)\n" +
          indent(writeStep(element, s"$expression.get"), 4) + "\n  }\n}"
      case Value.ArrayOf(element) => writeCollectionStep(element, expression, isMap = false)
      case Value.MapOf(element) => writeCollectionStep(element, expression, isMap = true)
      case Value.Union(branches) =>
        val nullIndex = branches.indexWhere(isNull)
        if branches.size == 1 then
          s"$step.defer {\n  out.writeIndex(0)\n" + indent(writeStep(branches.head, expression), 2) + "\n}"
        else if nullIndex >= 0 then
          s"$step.defer {\n  if $expression.isEmpty then {\n    out.writeIndex($nullIndex)\n    out.writeNull()\n    $step.done(())\n  } else {\n" +
            indent(writeUnionStep(branches.zipWithIndex.filterNot((branch, _) => isNull(branch)), s"$expression.get"), 4) + "\n  }\n}"
        else writeUnionStep(branches.zipWithIndex, expression)
      case _ => s"$step.delay { ${write(value, expression)} }"

    private def writeUnionStep(branches: Vector[(Value, Int)], expression: String): String =
      val cases = branches.map { (branch, index) =>
        val binding = fresh("branch")
        val (pattern, typed) = branch match
          case Value.ArrayOf(_) => ("_root_.scala.collection.immutable.Vector[?]", s"$binding.asInstanceOf[${scalaType(branch)}]")
          case Value.MapOf(_) => ("_root_.scala.collection.immutable.Map[?, ?]", s"$binding.asInstanceOf[${scalaType(branch)}]")
          case _ => (scalaType(branch), binding)
        s"case $binding: $pattern =>\n" + indent(s"out.writeIndex($index)\n" + writeStep(branch, typed), 2)
      }.mkString("\n")
      s"$step.defer {\n  ($expression: _root_.scala.Any) match {\n" + indent(cases, 4) +
        "\n    case _ => throw new _root_.java.lang.IllegalArgumentException(\"Value does not match any Avro union branch\")\n  }\n}"

    private def writeCollectionStep(element: Value, expression: String, isMap: Boolean): String =
      val item = fresh("item")
      val kind = if isMap then "Map" else "Array"
      s"$stackSafe.write$kind[${scalaType(element)}](out, $expression) { $item =>\n" +
        indent(writeStep(element, item), 2) + "\n}"

    def write(value: Value, expression: String): String = value match
      case Value.Primitive(Schema.Type.NULL) => "out.writeNull()"
      case Value.Primitive(kind) => s"out.write${primitiveSuffix(kind)}($expression)"
      case Value.LogicalValue(logical) => writeLogical(logical, expression)
      case Value.WrappedLogical(logical) => writeLogical(logical, s"$expression.value")
      case Value.Named(name) => s"${ScalaNames.qualified(config.mappedFullName(name))}.codec.write($expression, out)"
      case Value.Optional(element, nullIndex, valueIndex) =>
        s"if $expression.isEmpty then {\n  out.writeIndex($nullIndex)\n  out.writeNull()\n} else {\n  out.writeIndex($valueIndex)\n" +
          indent(write(element, s"$expression.get"), 2) + "\n}"
      case Value.ArrayOf(Value.Primitive(Schema.Type.INT)) => s"out.writeIntArray($expression)"
      case Value.ArrayOf(Value.Primitive(Schema.Type.LONG)) => s"out.writeLongArray($expression)"
      case Value.ArrayOf(element) => writeCollection(element, expression, isMap = false)
      case Value.MapOf(element) => writeCollection(element, expression, isMap = true)
      case Value.Union(branches) =>
        val nullIndex = branches.indexWhere(isNull)
        if branches.size == 1 then "out.writeIndex(0)\n" + write(branches.head, expression)
        else if nullIndex >= 0 then
          s"if $expression.isEmpty then {\n  out.writeIndex($nullIndex)\n  out.writeNull()\n} else {\n" +
            indent(writeUnion(branches.zipWithIndex.filterNot((branch, _) => isNull(branch)), s"$expression.get"), 2) + "\n}"
        else writeUnion(branches.zipWithIndex, expression)

    private def writeUnion(branches: Vector[(Value, Int)], expression: String): String =
      val cases = branches.map { (branch, index) =>
        val binding = fresh("branch")
        val (pattern, typed) = branch match
          case Value.ArrayOf(_) => ("_root_.scala.collection.immutable.Vector[?]", s"$binding.asInstanceOf[${scalaType(branch)}]")
          case Value.MapOf(_) => ("_root_.scala.collection.immutable.Map[?, ?]", s"$binding.asInstanceOf[${scalaType(branch)}]")
          case _ => (scalaType(branch), binding)
        s"case $binding: $pattern =>\n" + indent(s"out.writeIndex($index)\n" + write(branch, typed), 2)
      }.mkString("\n")
      s"($expression: _root_.scala.Any) match {\n" + indent(cases, 2) +
        "\n  case _ => throw new _root_.java.lang.IllegalArgumentException(\"Value does not match any Avro union branch\")\n}"

    private def writeCollection(element: Value, expression: String, isMap: Boolean): String =
      val collection = fresh("entry")
      val item = fresh("item")
      val kind = if isMap then "Map" else "Array"
      // HashMap.foreachEntry traverses its nodes without Tuple2/iterator
      // allocation. Vector.foreach traverses its leaf arrays directly; both
      // retain collection order and the encoder's per-item callback contract.
      val traversal = if isMap then
        val key = fresh("key")
        s"$collection.foreachEntry { ($key, $item) =>\n  out.startItem()\n  out.writeString($key)\n" +
          indent(write(element, item), 2) + "\n}\n"
      else s"$collection.foreach { $item =>\n  out.startItem()\n" + indent(write(element, item), 2) + "\n}\n"
      s"val $collection = $expression\nout.write${kind}Start($collection.size)\n" + traversal +
        s"out.write${kind}End()"
