package avro2s.wire.compiler

import org.apache.avro.Schema
import SchemaModel.{Definition, Logical, Value}

final case class GeneratedSource(relativePath: String, content: String)

/** Schema-first generation. The emitted sources have no Apache Avro dependency. */
object CodeGenerator:
  def generate(schema: Schema): Vector[GeneratedSource] =
    val definitions = SchemaModel.definitions(schema)
    val byName = definitions.map(definition => definition.name -> definition).toMap
    definitions.map(generateDefinition(_, byName))

  private def generateDefinition(definition: Definition, definitions: Map[String, Definition]): GeneratedSource =
    val emitter = Emitter()
    val fullName = definition.name
    val parts = fullName.split("\\.").toVector
    val localName = ScalaNames.escaped(parts.last)
    val qualifiedName = ScalaNames.qualified(fullName)
    val header =
      "// Generated by avro2s.wire. Do not edit.\n" +
        (if parts.size > 1 then s"package ${parts.init.map(ScalaNames.escaped).mkString(".")}\n\n" else "\n")

    val (model, json, read, write, construct) = definition match
      case Definition.Record(_, fields, json) =>
        val parameters = fields.map { field =>
          s"${ScalaNames.escaped(field.scalaName)}: ${emitter.scalaType(field.value)}"
        }.mkString(", ")
        val reads = fields.zipWithIndex.map { (field, index) =>
          s"val field$index: ${emitter.scalaType(field.value)} = ${emitter.read(field.value)}"
        }
        val constructor = s"new $qualifiedName(${fields.indices.map(i => s"field$i").mkString(", ")})"
        val read = "in.enterRecord()\ntry {\n" + indent((reads :+ constructor).mkString("\n"), 2) +
          "\n} finally in.leaveRecord()"
        val writes = fields.map { field =>
          emitter.write(field.value, s"value.${ScalaNames.escaped(field.scalaName)}")
        }
        val construct = s"new $qualifiedName(${fields.zipWithIndex.map((field, index) => s"values($index).asInstanceOf[${emitter.scalaType(field.value)}]").mkString(", ")})"
        (s"final case class $localName($parameters)\n", json, read,
          if writes.isEmpty then "()" else writes.mkString("\n"), construct)

      case Definition.Enumeration(_, symbols, json) =>
        val cases = ScalaNames.memberNames(symbols, ScalaNames.enumMembers + parts.last, "symbol")
        val model = s"enum $localName:\n" + cases.map(name => s"  case ${ScalaNames.escaped(name)}").mkString("\n") + "\n"
        val readCases = cases.zipWithIndex.map { (name, index) =>
          s"case $index => $qualifiedName.${ScalaNames.escaped(name)}"
        }.mkString("\n")
        val error = ScalaNames.literal(s"Invalid enum index for $fullName: ")
        val read = "in.readEnum() match {\n" + indent(readCases, 2) +
          s"\n  case index => throw new _root_.avro2s.wire.runtime.AvroDecodingException($error + index)\n}"
        (model, json, read, "out.writeEnum(value.ordinal)", s"$qualifiedName.fromOrdinal(values(0).asInstanceOf[_root_.scala.Int])")

      case Definition.Fixed(_, size, logical, json) =>
        val message = ScalaNames.literal(s"$fullName requires exactly $size bytes")
        val valueType = logical.fold("_root_.avro2s.wire.runtime.Bytes")(_.scalaType)
        val model = s"final case class $localName(value: $valueType)" +
          logical.fold(s":\n  _root_.scala.Predef.require(value.size == $size, $message)\n")(_ => "\n")
        val read = logical.fold(s"in.readFixed($size)")(emitter.readLogical(_, Some(size)))
        val write = logical.fold("out.writeFixed(value.value)")(emitter.writeLogical(_, "value.value", Some(size)))
        (model, json, s"new $qualifiedName($read)", write,
          s"new $qualifiedName(values(0).asInstanceOf[$valueType])")

    val references = reachableDefinitions(definition, definitions).map { name =>
      s"case ${ScalaNames.literal(name)} => ${ScalaNames.qualified(name)}.codec"
    }.mkString("\n")

    val companion = s"\nobject $localName:\n" +
      s"  val schemaJson: _root_.java.lang.String = ${ScalaNames.stringExpression(json)}\n\n" +
      s"  given codec: _root_.avro2s.wire.runtime.AvroCodec[$qualifiedName] with\n" +
      s"    override val schemaJson: _root_.java.lang.String = $qualifiedName.schemaJson\n\n" +
      s"    override def read(in: _root_.avro2s.wire.runtime.AvroInput): $qualifiedName =\n" + indent(read, 6) + "\n\n" +
      s"    override def write(value: $qualifiedName, out: _root_.avro2s.wire.runtime.AvroOutput): _root_.scala.Unit =\n" +
      indent(write, 6) + "\n\n" +
      s"    override def construct(values: _root_.scala.Array[_root_.scala.Any]): $qualifiedName =\n" + indent(construct, 6) + "\n\n" +
      "    override def namedCodec(fullName: _root_.java.lang.String): _root_.avro2s.wire.runtime.AvroCodec[?] =\n" +
      "      fullName match {\n" + indent(references, 8) + "\n        case _ => super.namedCodec(fullName)\n      }\n"
    GeneratedSource(parts.mkString("/") + ".scala", header + model + companion)

  private def reachableDefinitions(root: Definition, definitions: Map[String, Definition]): Vector[String] =
    val seen = scala.collection.mutable.Set.empty[String]
    def visitValue(value: Value): Unit = value match
      case Value.Named(name) => visitDefinition(definitions(name))
      case Value.ArrayOf(element) => visitValue(element)
      case Value.MapOf(element) => visitValue(element)
      case Value.Optional(element, _, _) => visitValue(element)
      case Value.Union(branches) => branches.foreach(visitValue)
      case _ => ()
    def visitDefinition(definition: Definition): Unit =
      if seen.add(definition.name) then definition match
        case Definition.Record(_, fields, _) => fields.foreach(field => visitValue(field.value))
        case _ => ()
    visitDefinition(root)
    seen.toVector.sorted

  private def indent(text: String, spaces: Int): String =
    text.linesIterator.map(" " * spaces + _).mkString("\n")

  private final class Emitter:
    private var sequence = 0
    private def fresh(prefix: String): String =
      sequence += 1
      s"${prefix}$sequence"

    def scalaType(value: Value): String = value match
      case Value.Primitive(Schema.Type.NULL)    => "_root_.scala.Null"
      case Value.Primitive(Schema.Type.BOOLEAN) => "_root_.scala.Boolean"
      case Value.Primitive(Schema.Type.INT)     => "_root_.scala.Int"
      case Value.Primitive(Schema.Type.LONG)    => "_root_.scala.Long"
      case Value.Primitive(Schema.Type.FLOAT)   => "_root_.scala.Float"
      case Value.Primitive(Schema.Type.DOUBLE)  => "_root_.scala.Double"
      case Value.Primitive(Schema.Type.STRING)  => "_root_.java.lang.String"
      case Value.Primitive(Schema.Type.BYTES)   => "_root_.avro2s.wire.runtime.Bytes"
      case Value.Primitive(other) => throw GenerationException(s"Unexpected primitive schema: $other")
      case Value.LogicalValue(logical) => logical.scalaType
      case Value.WrappedLogical(logical) => s"_root_.avro2s.wire.runtime.$logical"
      case Value.Named(name) => ScalaNames.qualified(name)
      case Value.ArrayOf(element) => s"_root_.scala.collection.immutable.Vector[${scalaType(element)}]"
      case Value.MapOf(element) => s"_root_.scala.collection.immutable.Map[_root_.java.lang.String, ${scalaType(element)}]"
      case Value.Optional(element, _, _) => s"_root_.scala.Option[${scalaType(element)}]"
      case Value.Union(branches) =>
        val nonNull = branches.filterNot(isNull)
        val union = nonNull.map(scalaType).mkString(" | ")
        if nonNull.isEmpty then "_root_.scala.Null"
        else if nonNull.size != branches.size then s"_root_.scala.Option[$union]"
        else union

    private def isNull(value: Value): Boolean = value == Value.Primitive(Schema.Type.NULL)

    def readLogical(logical: Logical, fixedSize: Option[Int] = None): String =
      val (method, arguments) = logicalArguments(logical, fixedSize)
      s"_root_.avro2s.wire.runtime.LogicalValues.read$method(in$arguments)"

    def writeLogical(logical: Logical, expression: String, fixedSize: Option[Int] = None): String =
      val (method, arguments) = logicalArguments(logical, fixedSize)
      s"_root_.avro2s.wire.runtime.LogicalValues.write$method($expression, out$arguments)"

    private def logicalArguments(logical: Logical, fixedSize: Option[Int]): (String, String) = logical match
      case Logical.Decimal(precision, scale) => fixedSize match
        case Some(size) => ("FixedDecimal", s", $size, $precision, $scale")
        case None => ("Decimal", s", $precision, $scale")
      case Logical.Uuid if fixedSize.nonEmpty => ("FixedUuid", "")
      case other => (other.toString, "")

    private def primitiveSuffix(kind: Schema.Type): String = kind match
      case Schema.Type.BOOLEAN => "Boolean"
      case Schema.Type.INT     => "Int"
      case Schema.Type.LONG    => "Long"
      case Schema.Type.FLOAT   => "Float"
      case Schema.Type.DOUBLE  => "Double"
      case Schema.Type.STRING  => "String"
      case Schema.Type.BYTES   => "Bytes"
      case other => throw GenerationException(s"Unexpected binary primitive: $other")

    def read(value: Value): String = value match
      case Value.Primitive(Schema.Type.NULL) => "{ in.readNull(); null }"
      case Value.Primitive(kind) => s"in.read${primitiveSuffix(kind)}()"
      case Value.LogicalValue(logical) => readLogical(logical)
      case Value.WrappedLogical(logical) => s"new _root_.avro2s.wire.runtime.$logical(${readLogical(logical)})"
      case Value.Named(name) => s"${ScalaNames.qualified(name)}.codec.read(in)"
      case Value.Optional(element, nullIndex, valueIndex) =>
        "in.readIndex() match {\n" +
          s"  case $nullIndex => in.readNull(); _root_.scala.None\n" +
          s"  case $valueIndex => _root_.scala.Some(${read(element)})\n" +
          "  case index => throw new _root_.avro2s.wire.runtime.AvroDecodingException(\"Invalid nullable union index: \" + index)\n}"
      case Value.ArrayOf(element) => readCollection(element, isMap = false)
      case Value.MapOf(element) => readCollection(element, isMap = true)
      case Value.Union(branches) =>
        val optional = branches.size > 1 && branches.exists(isNull)
        val cases = branches.zipWithIndex.map { (branch, index) =>
          val result =
            if optional && isNull(branch) then "{ in.readNull(); _root_.scala.None }"
            else if optional then s"_root_.scala.Some(${read(branch)})"
            else read(branch)
          s"case $index => $result"
        }.mkString("\n")
        "in.readIndex() match {\n" + indent(cases, 2) +
          "\n  case index => throw new _root_.avro2s.wire.runtime.AvroDecodingException(\"Invalid union index: \" + index)\n}"

    private def readCollection(element: Value, isMap: Boolean): String =
      val builder = fresh("builder")
      val remaining = fresh("remaining")
      val key = fresh("key")
      val item = fresh("item")
      val collection = if isMap then "Map" else "Vector"
      val arguments = if isMap then s"_root_.java.lang.String, ${scalaType(element)}" else scalaType(element)
      val start = if isMap then "readMapStart" else "readArrayStart"
      val next = if isMap then "mapNext" else "arrayNext"
      val entry =
        if isMap then s"val $key = in.readString()\nval $item: ${scalaType(element)} = ${read(element)}\n$builder += (($key, $item))"
        else s"$builder += (${read(element)})"
      s"{\n  var $remaining = in.$start()\n" +
        s"  if $remaining == 0L then _root_.scala.collection.immutable.$collection.empty[$arguments]\n" +
        s"  else {\n    val $builder = _root_.scala.collection.immutable.$collection.newBuilder[$arguments]\n" +
        s"    while $remaining != 0L do {\n" +
        s"      while $remaining > 0L do {\n" + indent(entry, 8) + s"\n        $remaining -= 1L\n      }\n" +
        s"      $remaining = in.$next()\n    }\n    $builder.result()\n  }\n}"

    def write(value: Value, expression: String): String = value match
      case Value.Primitive(Schema.Type.NULL) => "out.writeNull()"
      case Value.Primitive(kind) => s"out.write${primitiveSuffix(kind)}($expression)"
      case Value.LogicalValue(logical) => writeLogical(logical, expression)
      case Value.WrappedLogical(logical) => writeLogical(logical, s"$expression.value")
      case Value.Named(name) => s"${ScalaNames.qualified(name)}.codec.write($expression, out)"
      case Value.Optional(element, nullIndex, valueIndex) =>
        s"if $expression.isEmpty then {\n  out.writeIndex($nullIndex)\n  out.writeNull()\n} else {\n  out.writeIndex($valueIndex)\n" +
          indent(write(element, s"$expression.get"), 2) + "\n}"
      case Value.ArrayOf(element) => writeCollection(element, expression, isMap = false)
      case Value.MapOf(element) => writeCollection(element, expression, isMap = true)
      case Value.Union(branches) =>
        val nullIndex = branches.indexWhere(isNull)
        if branches.size == 1 then "out.writeIndex(0)\n" + write(branches.head, expression)
        else if nullIndex >= 0 then
          s"if $expression.isEmpty then {\n  out.writeIndex($nullIndex)\n  out.writeNull()\n} else {\n" +
            indent(writeUnion(branches.zipWithIndex.filterNot((branch, _) => isNull(branch)), s"$expression.get"), 2) + "\n}"
        else writeUnion(branches.zipWithIndex, expression)

    private def writeUnion(branches: Vector[(Value, Int)], expression: String): String =
      val cases = branches.map { (branch, index) =>
        val binding = fresh("branch")
        val (pattern, typed) = branch match
          case Value.ArrayOf(_) => ("_root_.scala.collection.immutable.Vector[?]", s"$binding.asInstanceOf[${scalaType(branch)}]")
          case Value.MapOf(_) => ("_root_.scala.collection.immutable.Map[?, ?]", s"$binding.asInstanceOf[${scalaType(branch)}]")
          case _ => (scalaType(branch), binding)
        s"case $binding: $pattern =>\n" + indent(s"out.writeIndex($index)\n" + write(branch, typed), 2)
      }.mkString("\n")
      s"($expression: _root_.scala.Any) match {\n" + indent(cases, 2) +
        "\n  case _ => throw new _root_.java.lang.IllegalArgumentException(\"Value does not match any Avro union branch\")\n}"

    private def writeCollection(element: Value, expression: String, isMap: Boolean): String =
      val iterator = fresh("iterator")
      val entry = fresh("entry")
      val kind = if isMap then "Map" else "Array"
      val body =
        if isMap then s"val $entry = $iterator.next()\nout.writeString($entry._1)\n" + write(element, s"$entry._2")
        else s"val $entry = $iterator.next()\n" + write(element, entry)
      s"out.write${kind}Start($expression.size)\nval $iterator = $expression.iterator\n" +
        s"while $iterator.hasNext do {\n  out.startItem()\n" + indent(body, 2) + "\n}\n" +
        s"out.write${kind}End()"
