package avrogen.compiler

import org.apache.avro.Schema
import SchemaModel.{Definition, Value}

final case class GeneratedSource(relativePath: String, content: String)

/** Schema-first generation. The emitted sources have no Apache Avro dependency. */
object CodeGenerator:
  def generate(schema: Schema): Vector[GeneratedSource] =
    SchemaModel.definitions(schema).map(generateDefinition)

  private def generateDefinition(definition: Definition): GeneratedSource =
    val emitter = Emitter()
    val fullName = definition.name
    val parts = fullName.split("\\.").toVector
    val localName = ScalaNames.escaped(parts.last)
    val qualifiedName = ScalaNames.qualified(fullName)
    val header =
      "// Generated by avrogen. Do not edit.\n" +
        (if parts.size > 1 then s"package ${parts.init.map(ScalaNames.escaped).mkString(".")}\n\n" else "\n")

    val (model, json, read, write) = definition match
      case Definition.Record(_, fields, json) =>
        val parameters = fields.map { field =>
          s"${ScalaNames.escaped(field.scalaName)}: ${emitter.scalaType(field.value)}"
        }.mkString(", ")
        val reads = fields.zipWithIndex.map { (field, index) =>
          s"val field$index = ${emitter.read(field.value)}"
        }
        val constructor = s"new $qualifiedName(${fields.indices.map(i => s"field$i").mkString(", ")})"
        val read = "in.enterRecord()\ntry {\n" + indent((reads :+ constructor).mkString("\n"), 2) +
          "\n} finally in.leaveRecord()"
        val writes = fields.map { field =>
          emitter.write(field.value, s"value.${ScalaNames.escaped(field.scalaName)}")
        }
        (s"final case class $localName($parameters)\n", json, read,
          if writes.isEmpty then "()" else writes.mkString("\n"))

      case Definition.Enumeration(_, symbols, json) =>
        val cases = ScalaNames.memberNames(symbols, ScalaNames.enumMembers + parts.last, "symbol")
        val model = s"enum $localName:\n" + cases.map(name => s"  case ${ScalaNames.escaped(name)}").mkString("\n") + "\n"
        val readCases = cases.zipWithIndex.map { (name, index) =>
          s"case $index => $qualifiedName.${ScalaNames.escaped(name)}"
        }.mkString("\n")
        val error = ScalaNames.literal(s"Invalid enum index for $fullName: ")
        val read = "in.readEnum() match {\n" + indent(readCases, 2) +
          s"\n  case index => throw new _root_.avrogen.runtime.AvroDecodingException($error + index)\n}"
        (model, json, read, "out.writeEnum(value.ordinal)")

      case Definition.Fixed(_, size, json) =>
        val message = ScalaNames.literal(s"$fullName requires exactly $size bytes")
        val model = s"final case class $localName(value: _root_.avrogen.runtime.Bytes):\n" +
          s"  _root_.scala.Predef.require(value.size == $size, $message)\n"
        (model, json, s"new $qualifiedName(in.readFixed($size))", "out.writeFixed(value.value)")

    val companion = s"\nobject $localName:\n" +
      s"  val schemaJson: _root_.java.lang.String = ${ScalaNames.stringExpression(json)}\n\n" +
      s"  given codec: _root_.avrogen.runtime.AvroCodec[$qualifiedName] with\n" +
      s"    override val schemaJson: _root_.java.lang.String = $qualifiedName.schemaJson\n\n" +
      s"    override def read(in: _root_.avrogen.runtime.AvroInput): $qualifiedName =\n" + indent(read, 6) + "\n\n" +
      s"    override def write(value: $qualifiedName, out: _root_.avrogen.runtime.AvroOutput): _root_.scala.Unit =\n" +
      indent(write, 6) + "\n"
    GeneratedSource(parts.mkString("/") + ".scala", header + model + companion)

  private def indent(text: String, spaces: Int): String =
    text.linesIterator.map(" " * spaces + _).mkString("\n")

  private final class Emitter:
    private var sequence = 0
    private def fresh(prefix: String): String =
      sequence += 1
      s"${prefix}$sequence"

    def scalaType(value: Value): String = value match
      case Value.Primitive(Schema.Type.NULL)    => "_root_.scala.Null"
      case Value.Primitive(Schema.Type.BOOLEAN) => "_root_.scala.Boolean"
      case Value.Primitive(Schema.Type.INT)     => "_root_.scala.Int"
      case Value.Primitive(Schema.Type.LONG)    => "_root_.scala.Long"
      case Value.Primitive(Schema.Type.FLOAT)   => "_root_.scala.Float"
      case Value.Primitive(Schema.Type.DOUBLE)  => "_root_.scala.Double"
      case Value.Primitive(Schema.Type.STRING)  => "_root_.java.lang.String"
      case Value.Primitive(Schema.Type.BYTES)   => "_root_.avrogen.runtime.Bytes"
      case Value.Primitive(other) => throw GenerationException(s"Unexpected primitive schema: $other")
      case Value.Named(name) => ScalaNames.qualified(name)
      case Value.ArrayOf(element) => s"_root_.scala.collection.immutable.Vector[${scalaType(element)}]"
      case Value.MapOf(element) => s"_root_.scala.collection.immutable.Map[_root_.java.lang.String, ${scalaType(element)}]"
      case Value.Optional(element, _, _) => s"_root_.scala.Option[${scalaType(element)}]"

    private def primitiveSuffix(kind: Schema.Type): String = kind match
      case Schema.Type.BOOLEAN => "Boolean"
      case Schema.Type.INT     => "Int"
      case Schema.Type.LONG    => "Long"
      case Schema.Type.FLOAT   => "Float"
      case Schema.Type.DOUBLE  => "Double"
      case Schema.Type.STRING  => "String"
      case Schema.Type.BYTES   => "Bytes"
      case other => throw GenerationException(s"Unexpected binary primitive: $other")

    def read(value: Value): String = value match
      case Value.Primitive(Schema.Type.NULL) => "{ in.readNull(); null }"
      case Value.Primitive(kind) => s"in.read${primitiveSuffix(kind)}()"
      case Value.Named(name) => s"${ScalaNames.qualified(name)}.codec.read(in)"
      case Value.Optional(element, nullIndex, valueIndex) =>
        "in.readIndex() match {\n" +
          s"  case $nullIndex => in.readNull(); _root_.scala.None\n" +
          s"  case $valueIndex => _root_.scala.Some(${read(element)})\n" +
          "  case index => throw new _root_.avrogen.runtime.AvroDecodingException(\"Invalid nullable union index: \" + index)\n}"
      case Value.ArrayOf(element) => readCollection(element, isMap = false)
      case Value.MapOf(element) => readCollection(element, isMap = true)

    private def readCollection(element: Value, isMap: Boolean): String =
      val builder = fresh("builder")
      val remaining = fresh("remaining")
      val key = fresh("key")
      val item = fresh("item")
      val collection = if isMap then "Map" else "Vector"
      val arguments = if isMap then s"_root_.java.lang.String, ${scalaType(element)}" else scalaType(element)
      val start = if isMap then "readMapStart" else "readArrayStart"
      val next = if isMap then "mapNext" else "arrayNext"
      val entry =
        if isMap then s"val $key = in.readString()\nval $item = ${read(element)}\n$builder += (($key, $item))"
        else s"$builder += (${read(element)})"
      s"{\n  val $builder = _root_.scala.collection.immutable.$collection.newBuilder[$arguments]\n" +
        s"  var $remaining = in.$start()\n  while $remaining != 0L do {\n" +
        s"    while $remaining > 0L do {\n" + indent(entry, 6) + s"\n      $remaining -= 1L\n    }\n" +
        s"    $remaining = in.$next()\n  }\n  $builder.result()\n}"

    def write(value: Value, expression: String): String = value match
      case Value.Primitive(Schema.Type.NULL) => "out.writeNull()"
      case Value.Primitive(kind) => s"out.write${primitiveSuffix(kind)}($expression)"
      case Value.Named(name) => s"${ScalaNames.qualified(name)}.codec.write($expression, out)"
      case Value.Optional(element, nullIndex, valueIndex) =>
        s"if $expression.isEmpty then {\n  out.writeIndex($nullIndex)\n  out.writeNull()\n} else {\n  out.writeIndex($valueIndex)\n" +
          indent(write(element, s"$expression.get"), 2) + "\n}"
      case Value.ArrayOf(element) => writeCollection(element, expression, isMap = false)
      case Value.MapOf(element) => writeCollection(element, expression, isMap = true)

    private def writeCollection(element: Value, expression: String, isMap: Boolean): String =
      val iterator = fresh("iterator")
      val entry = fresh("entry")
      val kind = if isMap then "Map" else "Array"
      val body =
        if isMap then s"val $entry = $iterator.next()\nout.writeString($entry._1)\n" + write(element, s"$entry._2")
        else s"val $entry = $iterator.next()\n" + write(element, entry)
      s"out.write${kind}Start($expression.size)\nval $iterator = $expression.iterator\n" +
        s"while $iterator.hasNext do {\n  out.startItem()\n" + indent(body, 2) + "\n}\n" +
        s"out.write${kind}End()"
